### ISSUE TITLE
Could be updated for users in the metric system

### ISSUE THREAD

**Issue by kylesnod** [jfkirk/pelotonnes#1]
https://github.com/jfkirk/pelotonnes/blob/8155164436c098ba4ebc2faa75bbba6137481f86/src/aggregation.py#L136

**Comment by jfkirk** [comment]
Hey @kylesnod good idea - does the Peloton .csv schema change for users who are in metric? If so, do you happen to have the column headers for a metric .csv?

**Comment by jfkirk** [comment]
I just updated the aggregations to support CSVs with metric units. The analyses are all still in customary units but, with a little spare time, I'll add a toggle for those too.

https://github.com/jfkirk/pelotonnes/commit/f39cc17f33f7e11c21675390a7ae999e977e9a79
